name2config = {
    "select_mahjong_series": ["select_mahjong", "select_mahjong_spatial", "select_unique_type_mahjong", "select_mahjong_semantic"],
    "select_poker_series": ["select_poker", "select_poker_spatial", "select_nth_largest_poker", "select_poker_semantic"],
    "select_chemistry_tube_series": ["select_chemistry_tube", "select_chemistry_tube_spatial", "select_chemistry_tube_common_sense", "select_chemistry_tube_semantic"],
    "select_fruit_series": ["select_fruit", "select_fruit_spatial", "select_fruit_common_sense", "select_fruit_semantic"],
    "add_condiment_series": ["add_condiment", "add_condiment_spatial", "add_condiment_common_sense", "add_condiment_semantic"],
    "insert_flower_series": ["insert_flower", "insert_flower_spatial", "insert_flower_common_sense", "insert_flower_semantic", "insert_bloom_flower"],
    "select_book_series": ["select_book", "select_book_spatial", "select_specific_type_book", "select_book_semantic"],
    "select_billiards_series": ["select_billiards", "select_billiards_spatial", "select_billiards_common_sense", "select_billiards_semantic"],
    "select_drink_series": ["select_drink", "select_drink_spatial", "select_drink_common_sense", "select_drink_semantic"],
    "select_toy_series": ["select_toy", "select_toy_spatial", "select_toy_common_sense", "select_toy_semantic"],
    "select_ingredient_series": ["select_ingredient", "select_ingredient_spatial", "select_ingredient_common_sense", "select_ingredient_semantic"],
    "select_painting_series":["select_painting", "put_box_on_painting", "select_painting_semantic"],
    "physical_qa_series":["friction_qa", "density_qa", "magnetism_qa", "reflection_qa", "speed_of_sound_qa", "thermal_expansion_qa", "weight_qa"],
    # composite tasks
    "texas_holdem_series":["texas_holdem", "texas_holdem_explore"],
    "set_dining_table_series":["set_dining_table", "set_dining_left_hand", "set_dining_chopstick"],
    "cool_drink_series":["cool_drink", "take_out_cool_drink"],
    "heat_food_series":["heat_food"],
    "get_coffee_series":["get_coffee", "get_coffee_with_sugar", "get_coffee_with_milk"],
    "hammer_nail_series":["hammer_loose_nail", "assemble_hammer", "hammer_nail_and_hang_picture"],
    "make_juice_series":["make_juice"],
    "seesaw_series":["simple_seesaw_use", "complex_seesaw_use"],
    "set_study_table_series":["set_study_table"],

    "heat_chemistry_tube_series":["heat_chemistry_tube"],
    "insert_tube_series":["insert_tube"],
    "shake_tube_series":["shake_tube"],
    "lift_petri_dish_series":["lift_petri_dish"],
    "pour_liquid_from_test_tube_into_beaker_series":["pour_liquid_from_test_tube_into_beaker"],
    "pour_pour_series":["pour_pour"],
    "test_chemistry_beaker_series":["test_chemistry_beaker"],
    "lift_beaker_series":["lift_beaker"],
    "lift_flask_series":["lift_flask"],
    "lift_beaker_series":["lift_beaker"],
    "place_beaker_pres_heat_device_series":["place_beaker_pres_heat_device"],
    "pick_stir_series":["pick_stir"],
    "wait_for_object_lift_beaker_series":["wait_for_object_lift_beaker"],
    "pick_up_small_beaker_series":["pick_up_small_beaker"],
    "lift_tube_series":["lift_tube"],
    "insert_stirring_rod_series":["insert_stirring_rod"],
    "pick_tube_shake_tube_series":["pick_tube_shake_tube"],
    "shake_beaker_series":["shake_beaker"],
    "weight_beaker_series":["weight_beaker"],
    "pick_pill_bottle_lift_pill_bottle_series":["pick_pill_bottle_lift_pill_bottle"],
    "unscrew_pill_bottle_series":["unscrew_pill_bottle"],
    "unscrew_asprin_pill_bottle_series":["unscrew_asprin_pill_bottle"],
    "pour_tube_insert_tube_series":["pour_tube_insert_tube"],
    "stir_beaker_series":["stir_beaker"],
    "place_beaker_on_the_mat_series":["place_beaker_on_the_mat"],
    "place_flask_on_the_mat_series":["place_flask_on_the_mat"],
    "pour_beaker_series":["pour_beaker"],
    "pick_cylinder_mid_pour_object_series":["pick_cylinder_mid_pour_object"],
    "pour_cylinder_series":["pour_cylinder"],
    "pick_funnel":["pick_funnel"],
    "two_tube_pour_stir_series":["two_tube_pour_stir"],
}