from VLABench.tasks.hierarchical_tasks.primitive.add_condiment_series import *
from VLABench.tasks.hierarchical_tasks.primitive.insert_flower_series import *
from VLABench.tasks.hierarchical_tasks.primitive.physical_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_billiards_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_book_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_chemistry_tube_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_drink_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_fruit_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_ingredient_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_mahjong_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_painting_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_poker_series import *
from VLABench.tasks.hierarchical_tasks.primitive.select_toy_series import *

from VLABench.tasks.hierarchical_tasks.primitive.move_petri_dish_series import *
from VLABench.tasks.hierarchical_tasks.primitive.rotate_beaker_series import *
from VLABench.tasks.hierarchical_tasks.primitive.heat_chemistry_tube_series import *
from VLABench.tasks.hierarchical_tasks.primitive.insert_tube_series import *
from VLABench.tasks.hierarchical_tasks.primitive.shake_tube_series import *
from VLABench.tasks.hierarchical_tasks.primitive.lift_petri_dish_series import *
from VLABench.tasks.hierarchical_tasks.primitive.pour_liquid_from_test_tube_into_beaker_series import *
from VLABench.tasks.hierarchical_tasks.primitive.pick_stir_series import *
from VLABench.tasks.hierarchical_tasks.primitive.wait_for_object_lift_beaker_series import *